### ISSUE TITLE
vtcrypt: keytool incompatibility

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanElbert/vt-middleware#4]
```
Using the keystore script to export a certificate from a PKCS#12 file does
not work the same as the keytool command.

keystore -export -keystore <pkcs12_file> -storepass <passwd> -storetype
PKCS12 -alias <alias> -cert <cert_file>
produced:
java.lang.NullPointerException
    at
edu.vt.middleware.crypt.util.CryptWriter.writeEncodedCertificate(CryptWriter.jav
a:205)
    at
edu.vt.middleware.crypt.util.CryptWriter.writeEncodedCertificate(CryptWriter.jav
a:181)
    at edu.vt.middleware.crypt.KeyStoreCli.doExport(KeyStoreCli.java:306)
    at edu.vt.middleware.crypt.KeyStoreCli.dispatch(KeyStoreCli.java:171)
    at edu.vt.middleware.crypt.AbstractCli.performAction(AbstractCli.java:77)
    at edu.vt.middleware.crypt.KeyStoreCli.main(KeyStoreCli.java:96)

keytool -export -keystore <pkcs12_file> -storepass <passwd> -storetype
PKCS12 -alias <alias> -file <cert_file>
worked as expected.

```

Original issue reported on code.google.com by `dfis...@gmail.com` on 29 Jun 2009 at 9:19

**Comment by GoogleCodeExporter** [comment]
```
Initial testing shows KeyStoreCli can operate on keystores that are _created_ 
with
the tool.  This was verified by adding a PKCS12 test case to the unit tests and
manually executing -export on the p12 keystore created in the test.
```

Original comment by `marvin.addison@gmail.com` on 30 Jun 2009 at 7:36
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
I can't reproduce this error.  I was able to export my VT NetCert certificate 
from
the p12 I received from CNS, which had a user-friendly alias.  I suspected 
maybe a
friendly alias was the problem, so created a new p12 file as follows:

 1. openssl genrsa -out test-rsa.pem -nopass 2048
 2. openssl req -x509 -key test-rsa.pem -new -days 365 -out test-cert.pem
 3. openssl pkcs12 -export -inkey test-rsa.pem -certfile test-cert.pem -out test.p12

Listing the keystore contents produced the following:
marvin:~/tmp$ keystore -list -keystore test.p12 -storepass password -storetype 
PKCS12

Alias name: 11bf4476e02763fac0162b9d76706cf39003129a
Creation date: Tue Jun 30 15:54:48 EDT 2009
Entry type: keyEntry
Certificate chain length: 1
===== Certificate [0] =====
Subject: DC=edu,DC=vt,C=US,ST=Virginia,L=Blacksburg,O=Virginia Polytechnic 
Institute
and State University,OU=Middleware,CN=marvin test cert
Issuer: DC=edu,DC=vt,C=US,ST=Virginia,L=Blacksburg,O=Virginia Polytechnic 
Institute
and State University,OU=Middleware,CN=marvin test cert
Serial: 00:EB:05:E8:B7:52:1B:B2:EC
Valid not before: Tue Jun 30 15:52:58 EDT 2009
Valid not after: Wed Jun 30 15:52:58 EDT 2010
MD5 fingerprint: 41:4D:26:32:A1:23:5C:87:81:B3:FE:5F:34:BB:C6:B6
SHA1 fingerprint: 11:BF:44:76:E0:27:63:FA:C0:16:2B:9D:76:70:6C:F3:90:03:12:9A

Note that the alias is merely the SHA1 fingerprint.  (Just for reference, the
Portecle GUI keystore tool shows the same.)

I was able to successfully export the cert from the p12 file:

marvin:~/tmp$ keystore -export -keystore test.p12 -storepass password -storetype
PKCS12 -alias 11bf4476e02763fac0162b9d76706cf39003129a -cert 
test-cert-exported.pem
Wrote certificate to test-cert-exported.pem

marvin:~/tmp$ openssl x509 -in test-cert-exported.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            eb:05:e8:b7:52:1b:b2:ec
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: DC=edu, DC=vt, C=US, ST=Virginia, L=Blacksburg, O=Virginia
Polytechnic Institute and State University, OU=Middleware, CN=marvin test cert
        Validity
            Not Before: Jun 30 19:52:58 2009 GMT
            Not After : Jun 30 19:52:58 2010 GMT
        Subject: DC=edu, DC=vt, C=US, ST=Virginia, L=Blacksburg, O=Virginia
Polytechnic Institute and State University, OU=Middleware, CN=marvin test cert
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:f7:93:6b:27:61:16:00:60:b3:db:fc:d8:33:b7:
                    ef:e3:c8:53:e3:77:74:d4:b5:8d:89:e6:10:35:a8:
                    d7:24:88:d4:5e:b0:1f:51:25:23:e0:e3:b3:85:2a:
                    e2:08:f7:2a:f6:2d:a4:20:a1:e8:74:1f:e4:4f:04:
                    40:5a:e8:36:90:ed:20:ca:14:a1:8d:78:eb:5a:88:
                    b6:2a:9d:63:9e:9d:c2:ed:35:cc:f2:63:55:aa:ec:
                    de:ae:14:1d:34:8c:39:b7:99:5b:62:d1:76:47:ad:
                    b1:f9:ef:8c:6a:c0:aa:db:5e:5b:6c:ad:71:63:02:
                    7d:1f:13:8f:dc:1b:9c:64:80:0a:12:05:36:6a:93:
                    8f:71:65:76:75:a7:26:33:bc:18:e0:7e:0c:d0:15:
                    a8:0f:86:58:09:67:e8:d7:de:6d:b3:d7:86:98:5d:
                    9f:e2:79:7f:8e:8d:d3:b1:2f:d8:44:05:8e:a9:69:
                    a9:41:48:13:8f:2d:9c:9d:e4:38:30:e5:20:6a:d6:
                    3a:29:1a:ca:96:18:ce:3a:42:97:20:02:26:c5:d8:
                    4b:ce:3c:09:a7:9f:a2:22:f9:8c:f1:85:6c:d8:0c:
                    be:63:bd:b3:25:84:04:fc:e9:b9:2b:dc:ee:91:5b:
                    41:a8:4e:48:d7:d4:d1:86:55:d7:c1:d4:34:3b:82:
                    72:3b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                1B:D4:13:22:99:6C:7C:95:54:E2:E5:61:07:71:79:DF:3A:3C:2C:0D
            X509v3 Authority Key Identifier: 
                keyid:1B:D4:13:22:99:6C:7C:95:54:E2:E5:61:07:71:79:DF:3A:3C:2C:0D
                DirName:/DC=edu/DC=vt/C=US/ST=Virginia/L=Blacksburg/O=Virginia
Polytechnic Institute and State University/OU=Middleware/CN=marvin test cert
                serial:EB:05:E8:B7:52:1B:B2:EC

            X509v3 Basic Constraints: 
                CA:TRUE
    Signature Algorithm: sha1WithRSAEncryption
        74:a0:15:09:c6:a1:38:d0:f9:87:9d:31:05:ae:26:9c:2b:35:
        66:73:7f:57:9e:82:6e:9b:b7:65:f9:cb:a7:f4:d4:00:85:f1:
        e8:0b:b9:72:f7:37:82:2f:86:3a:44:ba:9b:d4:ea:54:9f:9a:
        6b:f4:22:be:62:b5:2f:d0:89:8d:8f:ff:67:3f:ff:a6:1b:52:
        9a:cc:b0:33:bc:5f:cf:45:03:9d:75:b6:97:4c:2c:db:4a:7b:
        b6:36:3f:03:fc:7c:95:43:ba:9a:8a:6a:e1:d1:8c:3d:26:82:
        b9:4c:d3:d4:18:70:48:72:a4:68:56:07:fc:42:51:9c:d8:ad:
        2b:18:d4:9a:75:9b:ca:70:00:75:96:d3:0c:29:31:96:8f:cc:
        0e:32:53:d0:e6:ad:89:53:b9:d8:b9:a9:dc:b7:61:e9:55:47:
        86:da:f7:9c:3f:d1:ca:d0:5f:39:2d:a0:88:0c:d7:86:66:9a:
        29:6e:9f:b7:17:32:f7:1a:00:8e:54:61:fd:bb:62:97:61:cc:
        7f:68:34:7a:be:79:6c:05:47:e0:25:f4:c2:9e:1c:36:25:08:
        41:99:d4:f4:1e:7f:c5:29:8b:b7:85:87:ce:4a:d6:92:2e:e9:
        af:a4:cf:fa:eb:9e:ed:d5:50:70:72:e4:df:61:a2:f5:7a:4d:
        70:0b:7e:d7
-----BEGIN CERTIFICATE-----
MIIFVTCCBD2gAwIBAgIJAOsF6LdSG7LsMA0GCSqGSIb3DQEBBQUAMIHMMRMwEQYK
CZImiZPyLGQBGRYDZWR1MRIwEAYKCZImiZPyLGQBGRYCdnQxCzAJBgNVBAYTAlVT
MREwDwYDVQQIEwhWaXJnaW5pYTETMBEGA1UEBxMKQmxhY2tzYnVyZzE8MDoGA1UE
ChMzVmlyZ2luaWEgUG9seXRlY2huaWMgSW5zdGl0dXRlIGFuZCBTdGF0ZSBVbml2
ZXJzaXR5MRMwEQYDVQQLEwpNaWRkbGV3YXJlMRkwFwYDVQQDExBtYXJ2aW4gdGVz
dCBjZXJ0MB4XDTA5MDYzMDE5NTI1OFoXDTEwMDYzMDE5NTI1OFowgcwxEzARBgoJ
kiaJk/IsZAEZFgNlZHUxEjAQBgoJkiaJk/IsZAEZFgJ2dDELMAkGA1UEBhMCVVMx
ETAPBgNVBAgTCFZpcmdpbmlhMRMwEQYDVQQHEwpCbGFja3NidXJnMTwwOgYDVQQK
EzNWaXJnaW5pYSBQb2x5dGVjaG5pYyBJbnN0aXR1dGUgYW5kIFN0YXRlIFVuaXZl
cnNpdHkxEzARBgNVBAsTCk1pZGRsZXdhcmUxGTAXBgNVBAMTEG1hcnZpbiB0ZXN0
IGNlcnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD3k2snYRYAYLPb
/Ngzt+/jyFPjd3TUtY2J5hA1qNckiNResB9RJSPg47OFKuII9yr2LaQgoeh0H+RP
BEBa6DaQ7SDKFKGNeOtaiLYqnWOencLtNczyY1Wq7N6uFB00jDm3mVti0XZHrbH5
74xqwKrbXltsrXFjAn0fE4/cG5xkgAoSBTZqk49xZXZ1pyYzvBjgfgzQFagPhlgJ
Z+jX3m2z14aYXZ/ieX+OjdOxL9hEBY6paalBSBOPLZyd5Dgw5SBq1jopGsqWGM46
QpcgAibF2EvOPAmnn6Ii+YzxhWzYDL5jvbMlhAT86bkr3O6RW0GoTkjX1NGGVdfB
1DQ7gnI7AgMBAAGjggE2MIIBMjAdBgNVHQ4EFgQUG9QTIplsfJVU4uVhB3F53zo8
LA0wggEBBgNVHSMEgfkwgfaAFBvUEyKZbHyVVOLlYQdxed86PCwNoYHSpIHPMIHM
MRMwEQYKCZImiZPyLGQBGRYDZWR1MRIwEAYKCZImiZPyLGQBGRYCdnQxCzAJBgNV
BAYTAlVTMREwDwYDVQQIEwhWaXJnaW5pYTETMBEGA1UEBxMKQmxhY2tzYnVyZzE8
MDoGA1UEChMzVmlyZ2luaWEgUG9seXRlY2huaWMgSW5zdGl0dXRlIGFuZCBTdGF0
ZSBVbml2ZXJzaXR5MRMwEQYDVQQLEwpNaWRkbGV3YXJlMRkwFwYDVQQDExBtYXJ2
aW4gdGVzdCBjZXJ0ggkA6wXot1IbsuwwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B
AQUFAAOCAQEAdKAVCcahOND5h50xBa4mnCs1ZnN/V56Cbpu3ZfnLp/TUAIXx6Au5
cvc3gi+GOkS6m9TqVJ+aa/QivmK1L9CJjY//Zz//phtSmsywM7xfz0UDnXW2l0ws
20p7tjY/A/x8lUO6mopq4dGMPSaCuUzT1BhwSHKkaFYH/EJRnNitKxjUmnWbynAA
dZbTDCkxlo/MDjJT0OatiVO52Lmp3Ldh6VVHhtr3nD/RytBfOS2giAzXhmaaKW6f
txcy9xoAjlRh/btil2HMf2g0er55bAVH4CX0wp4cNiUIQZnU9B5/xSmLt4WHzkrW
ki7pr6TP+uue7dVQcHLk32Gi9XpNcAt+1w==
-----END CERTIFICATE-----

```

Original comment by `marvin.addison@gmail.com` on 30 Jun 2009 at 8:01

**Comment by GoogleCodeExporter** [comment]
```
Confirmed, the problem here has nothing to with PKCS#12.
The bug is in the handling of the alias command line option.
As far as I can tell, an alias can contain all sorts of fun characters.
Including spaces, apostrophes, semi-colons, etc.
The current implementation will break on any alias that contains a space.
Other characters may need to be tested as well.
```

Original comment by `dfis...@gmail.com` on 2 Jul 2009 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
Added alias parameter to KeyStoreCli unit test and tested following aliases:

vtcrypt
VT Crypt
vt,crypt
vt:crypt
vt;crypt
vt'crypt
vt-crypt

The only test case that failed was the one containing the alias "VT Crypt."  In 
the
keystore that was created, it only used the text preceding the space, "VT," for 
the
alias.

Improper handling of arguments containing spaces may be related to commons-cli
features/limitations, which I will investigate.
```

Original comment by `marvin.addison@gmail.com` on 2 Jul 2009 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
Further investigation absolves commons-cli argument handling.  Investigating 
the unit
test case containing the "VT Crypt" alias showed that it was failing for reasons
related to the test implementation.  Once that was corrected, the test case 
passed.

Repeated experimentation with the keystore script indicated that any alias 
containing
a space would be truncated to the part preceding the first space.  Apparently 
it is
the keystore script itself that is causing problems, based on different output 
from
executing the Java main class directly and the wrapper script.  The following 
command
imports the keypair correctly with the alias "Test Key Pair":

java -cp $CLASSPATH edu.vt.middleware.crypt.KeyStoreCli -import -keystore 
test.p12
-storetype PKCS12 -storepass password -cert test-cert.pem -key test-rsa.pem 
-alias
"Test Key Pair"

The following equivalent keystore script command incorrectly truncates the 
alias to
"Test":

keystore -import -keystore test.p12 -storetype PKCS12 -storepass password -cert
test-cert.pem -key test-rsa.pem -alias "Test Key Pair"
```

Original comment by `marvin.addison@gmail.com` on 6 Jul 2009 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
Fix committed in r319 of trunk.  Only *nix scripts required a fix since testing
showed Windows bat scripts handled spaces correctly.
```

Original comment by `marvin.addison@gmail.com` on 6 Jul 2009 at 7:14
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Fix verified by dfisher.
```

Original comment by `marvin.addison@gmail.com` on 28 Jul 2009 at 12:40
- Changed state: **Verified**
